version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  news-app:
    container_name: news-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    user: "node"
    working_dir: /server
    environment:
      - DB_URL=mongodb://mongo-db
    depends_on:
      - mongodb
    networks:
      - backend
    command: "npm start"
  client:
    container_name: client
    working_dir: /usr/src/app/client
    depends_on:
      - news-app
    user: "node"
    ports:
      - "5173:5173"
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    networks:
      - backend

volumes:
  mongodata:


networks:
  backend:
